sudo: required
language: generic
services:
  - docker


before_intsall:
  - docker build -t raghumanu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raghumanu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-405544463514"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY