sudo: required
language: generic
services:
  - docker


before_intsall:
  - docker build -t raghumanu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raghumanu/docker-react npm run test -- --coverage

